#!/bin/bash

module load trimmomatic/0.35

for prefix in $(cat ID.txt);

do

echo "now running trimmomatic on ${prefix}"

trimmomatic PE -threads 4 \
${prefix}_L001_R1.fastq.gz ${prefix}_L001_R2.fastq.gz \
${prefix}_L001_R1.trim.fastq.gz ${prefix}_L001_R1.untrim.fastq.gz ${prefix}_L001_R2.trim.fastq.gz ${prefix}_L001_R2.untrim.fastq.gz \
ILLUMINACLIP:TruSeq3-PE-2.fa:2:40:15:8:true MINLEN:50 SLIDINGWINDOW:4:20 LEADING:10

trimmomatic PE -threads 4 \
${prefix}_L002_R1.fastq.gz ${prefix}_L002_R2.fastq.gz \
${prefix}_L002_R1.trim.fastq.gz ${prefix}_L002_R1.untrim.fastq.gz ${prefix}_L002_R2.trim.fastq.gz ${prefix}_L002_R2.untrim.fastq.gz \
ILLUMINACLIP:TruSeq3-PE-2.fa:2:40:15:8:true MINLEN:50 SLIDINGWINDOW:4:20 LEADING:10

trimmomatic PE -threads 4 \
${prefix}_L003_R1.fastq.gz ${prefix}_L003_R2.fastq.gz \
${prefix}_L003_R1.trim.fastq.gz ${prefix}_L003_R1.untrim.fastq.gz ${prefix}_L003_R2.trim.fastq.gz ${prefix}_L003_R2.untrim.fastq.gz \
ILLUMINACLIP:TruSeq3-PE-2.fa:2:40:15:9:true MINLEN:50 SLIDINGWINDOW:4:20 LEADING:10

done
